[package]
edition = "2021"
name = "migration"
publish = false
version = "0.1.0"

[lib]
name = "migration"
path = "lib.rs"

[[bin]]
name = "champ-node-sql-migrate"
path = "main.rs"

[dependencies]
sea-schema = {version = "0.7.0", default-features = false, features = ["migration", "debug-print"]}
