site_name: champ
nav:
  - Overview: "index.md"
  - Developers:
      - Getting Started: "developers/setup.md"
      - Introduction: "developers/introduction.md"
      - Overview: "developers/overview.md"
      - RPC API: "developers/rpc-api.md"
      - CI/CD: "developers/cicd.md"
      - DockerZ: "developers/dockerz.md"
      - Voting: "developers/voting.md"
      - Security: "developers/security.md"
      - Storage:
          - SQL: "developers/storage/sql.md"
  - Operators:
      - Installation: "operators/installation.md"
      - Security: "operators/security.md"
