[package]
authors = ["The POG Contributors <contact@pog.network>"]
edition = "2021"
name = "champ-dev"

publish = false

[dev-dependencies]
cargo-release = "0.18"
convco = "0.3"

[dev-dependencies.cargo-husky]
features = ["user-hooks"]
version = "1"
