name: Canary Releases

on:
  push:
    branches:
      - main
    paths:
      - "**/*.rs"
  workflow_dispatch: {}

permissions:
  packages: write

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: pognetwork
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
      - uses: extractions/setup-just@v1
      - run: just canary-release
  e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set image env
        run: echo "IMAGE=$DOCKER_IMAGE" >> $GITHUB_ENV
      - name: E2E testing webhook
        uses: joelwmale/webhook-action@fd99bb3b8272237103e349e9bb4d9b0ead9a217c
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          body: '{"image": ${{env.IMAGE}}, "tag": ${{GITHUB_REF#refs/heads/}}, "commit": ${{ github.head_ref }}.${{ github.sha }}}'
