name: Canary Releases

on:
  push:
    branches:
      - main
    paths:
      - "**/*.rs"
  workflow_dispatch: {}

permissions:
  packages: write

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: pognetwork
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - uses: extractions/setup-just@v1
      - run: just docker canary $(git log -1 --pretty=format:%h)
      - name: Set image env
        run: echo "IMAGE=ghcr.io/pognetwork/champ" >> $GITHUB_ENV
      - name: Set tag env
        run: echo "TAG=canary-$(git log -1 --pretty=format:%h)" >> $GITHUB_ENV
      - uses: ./.github/workflows/e2e-test.yaml
        with: 
          image: ${{env.IMAGE}}
          tag: ${{env.TAG}}
          commit: ${{ github.head_ref }}.${{ github.sha }}
