name: Canary Releases

on:
  push:
    branches:
      - main
    paths:
      - "**/*.rs"
  workflow_dispatch: {}

permissions:
  packages: write

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: pognetwork
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
      - uses: extractions/setup-just@v1
      - run: |
          docker buildx create --use
          just release-docker linux/amd64,linux/arm64 ghcr.io/pognetwork/champ canary $(git log -1 --pretty=format:%h)
