name: Generate Release Notes

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Latest Release Notes
        run: |
          git checkout main
          git pull
      - name: "Create Github Release"
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE_NOTES.md
